config = {
    "experiment_name": "fusion_v4",
    "encoder_type": "fusion_v2",
    "data_root": "./dataset_100hz/train",
    "mean_path": "./stats_v3/mean.npy",
    "std_path":  "./stats_v3/std.npy",
    "frame_gap": 1,
    "image_size": None,
    "val_ratio": 6,
    "split_seed": 42,
    "encoder_kwargs": {
        "feature_dim": 256,
        "vision_feat_dim": 512,
        "inertial_feat_dim": 128,
        "hidden_dim": 512,
        "dropout": 0.2,
        "vision_pretrained": True,
    },
    "lambda_rot": 10.0,
    "lambda_homo": 1.0,
    "h4pt_scale": 400.0,
    "optimizer": "adam",
    "lr": 1e-3,
    "weight_decay": 0.0,
    "grad_clip": 1.0,
    "scheduler": "cosine",
    "min_lr": 1e-5,
    "epochs": 25,
    "batch_size": 32,
    "num_workers": 4,
    "log_every_n_steps": 50,
    "out_dir": "./runs/fusion_v4",
    "resume_from": None,
}
