config = {
    "experiment_name": "vision_v3",
    "encoder_type": "vision_v2",
    "data_root": "./dataset_100hz/train",
    "mean_path": "./stats_v3/mean.npy",
    "std_path":  "./stats_v3/std.npy",
    "frame_gap": 1,
    "image_size": None,
    "val_ratio": 6,
    "split_seed": 42,
    "encoder_kwargs": {
        "feature_dim": 512,
        "dropout": 0.1,
        "pretrained": True,
    },
    "lambda_rot": 10.0,
    "optimizer": "adam",
    "lr": 1e-3,
    "weight_decay": 0.0,
    "grad_clip": 1.0,
    "scheduler": "cosine",
    "min_lr": 1e-5,
    "epochs": 30,
    "batch_size": 32,
    "num_workers": 4,
    "log_every_n_steps": 50,
    "out_dir": "./runs/vision_v3",
    "resume_from": None,
}
